[package]
name = "rustow"
version = "0.4.0-beta"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
opt-level = 3
lto = true
panic = 'abort'
overflow-checks = false

