# made for rustfmt 1.5.2

#array_width = 60
#attr_fn_like_width = 70
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
#chain_width = 60
color = "Always"
combine_control_expr = true
#comment_width = 80
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
empty_item_single_line = true
enum_discrim_align_threshold = 50
fn_params_layout = "Tall"
fn_call_width = 50
fn_single_line = true
force_explicit_abi = true
force_multiline_blocks = true
format_code_in_doc_comments = true
#doc_comment_code_block_width = 100
format_generated_files = true
format_macro_matchers = true
format_macro_bodies = true
#format_strings = false
hard_tabs = false
hex_literal_case = "Upper"
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
#inline_attribute_width = 0
match_arm_blocks = false
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
#max_width = 100
merge_derives = true
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
#short_array_element_with_threshold = 10
#single_line_if_else_max_width = 50
space_after_colon = true
space_before_colon = false
spaces_around_ranges = true
struct_field_align_threshold = 50
struct_lit_single_line = true
struct_lit_width = 30
#struct_variant_width = 35
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
#use_small_heuristics = "Default"
use_try_shorthand = true
where_single_line = false
wrap_comments = true


#required_version = "1.5.1"
#version = "One"
#edition = "2021"
hide_parse_errors = false
error_on_line_overflow = false
error_on_unformatted = false
unstable_features = true
ignore = []
